---
title: "LeNews Analsiys"
output: html_notebook
---

This is an analysis of LeFloid News date

```{r}
mydata <- read.csv("lenews.csv")
mydata
```

# Welche Quellen werden angegeben?

Quellentransparenz.

```{r}
pattern <- "(http[^[:space:]]+)"
m <- gregexpr(pattern, mydata$description[1])
urls <- regmatches(mydata$description[1], m)
str(urls[1])
#grep(regex_url, mydata$description[1], value = TRUE)

```


```{r}
library(ggplot2)
ggplot(data = mydata) + 
  geom_point(mapping = aes(x = id, y = duration)) +
  labs(title = "Like_count vs. lenght") + 
  scale_x_discrete(breaks=NULL)
```

```{r}
ggplot(data = mydata, aes(x = like_count, y = dislike_count)) + 
  geom_point() +
  geom_smooth(se = FALSE) +
  labs(title = "Like vs. dislike in LeNews")
```
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Cmd+Option+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Cmd+Shift+K* to preview the HTML file).
